#!/usr/bin/env bash
# render_pandoc.sh — Pandoc citeproc wrapper for manuscript rendering with journal CSL.
# (Renamed from render_manuscript.sh on 2026-05-01 when relocated to /manage-refs.)
#
# Usage:
#   render_manuscript.sh -j <journal> -i <input.md> -b <refs.bib> [-o <out.docx>] [-t <reference.docx>] [-- <extra pandoc args>]
#
# Example:
#   render_manuscript.sh -j european-radiology -i manuscript.md -b references.bib -o manuscript_v4.docx
#
# Citation syntax in markdown body: [@bibkey] or [@key1; @key2]
# References section is auto-generated by pandoc citeproc — do NOT hand-write a References list.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CSL_DIR="${SCRIPT_DIR}/../citation_styles"

usage() {
  cat >&2 <<EOF
Usage: $(basename "$0") -j <journal> -i <input.md> -b <refs.bib> [-o <out>] [-t <reference.docx>] [-f <format>]

Options:
  -j  Journal CSL name (without .csl). Examples: european-radiology, radiology,
      american-journal-of-roentgenology, cardiovascular-and-interventional-radiology,
      korean-journal-of-radiology, vancouver. See \${CSL_DIR}/README.md.
  -i  Input markdown manuscript
  -b  BibTeX bibliography file
  -o  Output path (default: <input>.docx). Format inferred from extension.
  -t  Optional Word reference .docx for styles/fonts
  -f  Force output format (docx|pdf|html). Default: from -o extension or docx.
  -h  Help

Pass-through: any args after '--' go directly to pandoc.
EOF
  exit 1
}

JOURNAL=""
INPUT=""
BIB=""
OUTPUT=""
REFDOC=""
FORMAT=""

while getopts ":j:i:b:o:t:f:h" opt; do
  case "$opt" in
    j) JOURNAL="$OPTARG" ;;
    i) INPUT="$OPTARG" ;;
    b) BIB="$OPTARG" ;;
    o) OUTPUT="$OPTARG" ;;
    t) REFDOC="$OPTARG" ;;
    f) FORMAT="$OPTARG" ;;
    h|*) usage ;;
  esac
done
shift $((OPTIND - 1))

[[ -z "$JOURNAL" || -z "$INPUT" || -z "$BIB" ]] && usage

CSL_FILE="${CSL_DIR}/${JOURNAL}.csl"
if [[ ! -f "$CSL_FILE" ]]; then
  echo "ERROR: CSL not found: $CSL_FILE" >&2
  echo "Available styles:" >&2
  ls -1 "${CSL_DIR}" | grep '\.csl$' | sed 's/\.csl$//' | sed 's/^/  /' >&2
  exit 2
fi
[[ -f "$INPUT" ]] || { echo "ERROR: input not found: $INPUT" >&2; exit 2; }
[[ -f "$BIB" ]]   || { echo "ERROR: bib not found: $BIB" >&2; exit 2; }

if [[ -z "$OUTPUT" ]]; then
  OUTPUT="${INPUT%.*}.docx"
fi
if [[ -z "$FORMAT" ]]; then
  case "${OUTPUT##*.}" in
    docx) FORMAT="docx" ;;
    pdf)  FORMAT="pdf" ;;
    html) FORMAT="html" ;;
    *)    FORMAT="docx" ;;
  esac
fi

ARGS=(--citeproc --csl="$CSL_FILE" --bibliography="$BIB" -t "$FORMAT" -o "$OUTPUT")
[[ -n "$REFDOC" && -f "$REFDOC" ]] && ARGS+=(--reference-doc="$REFDOC")

echo "[render] journal=$JOURNAL csl=$(basename "$CSL_FILE") in=$INPUT bib=$BIB out=$OUTPUT" >&2
pandoc "${ARGS[@]}" "$@" "$INPUT"
echo "[render] ok → $OUTPUT" >&2
